name: compile
on: [push]
jobs:
  compile-windows:
    runs-on: windows-latest
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
            script: |
                core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
                core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
        env: 
            VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: .\\vcpkg integrate install
      - run: .\\vcpkg install
      - run: mkdir build
      - run: cmake -B build/ -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
      - run: cmake --build build/
      - run: echo ""
